version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "vignesh"
      MYSQL_DATABASE: "lms_project"
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pvignesh"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

  admin:
    build:
      context: .
      dockerfile: lms_admin/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://root:vignesh@db:3306/lms_project"
    ports:
      - "8001:8001"
    command: >
      sh -c "python manage.py migrate --fake-initial && 
             python manage.py migrate core --fake && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8001"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001/dashboard/')"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: lms_api/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://root:vignesh@db:3306/lms_project"
      JWT_SECRET: "devsecret"
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8002/docs')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
